import { StyleSheet, Font } from '@react-pdf/renderer';
Font.register({
  family: 'Ubuntu',
  fonts: [
    {
      src: 'https://fonts.gstatic.com/s/questrial/v13/QdVUSTchPBm7nuUeVf7EuStkm20oJA.ttf',
    },
    {
      src: 'https://fonts.gstatic.com/s/questrial/v13/QdVUSTchPBm7nuUeVf7EuStkm20oJA.ttf',
      fontWeight: 'bold',
    },
    {
      src: 'https://fonts.gstatic.com/s/questrial/v13/QdVUSTchPBm7nuUeVf7EuStkm20oJA.ttf',
      fontWeight: 'normal',
      fontStyle: 'italic',
    },
  ],
});

const styles = StyleSheet.create({
  main__page: {},
  main__body: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    marginleft: '20px',
  },
  main__body__2: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingLeft: '20px',
    paddingRight: '20px',
  },
  top__container: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '10px',
    paddingRight: '20px',
  },
  top__container_2: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginBottom: '15px',
    marginLeft: '20px',
  },
  logo: {
    width: '150px',
    height: '70px',
  },
  logo__2: {
    width: '130px',
    height: '70px',
  },
  account__opening: {
    backgroundColor: 'brown',
    borderRadius: '50px',
    padding: '10px',
  },
  account__opening__text: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: 'white',
  },
  open__account: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
  },
  form__block__container: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  line__one: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: '15px',
  },
  line__one__personal: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: '10px',
  },
  line__one__dob: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    gap: '35px',
  },
  line__one__photo: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: '15px',
    marginTop: '10px',
  },
  form__container: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  form__container_: {},
  form__container_block: {},
  martial__gender: {},
  form__container_block_marital: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  form__container__name__gender: {
    display: 'flex',
    flexDirection: 'row',
    gap: '15px',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  form__container_block__phone: {
    marginRight: '15px',
  },
  form__text: {
    fontSize: '8.5px',
    fontWeight: 'bold',
    color: 'brown',
  },
  form__text_marital: {
    fontSize: '8px',
    fontWeight: 'bold',
    width: '100px',
    textAlign: 'center',
    color: 'brown',
  },
  form__box: {
    border: '1px solid brown',
    width: '15px',
    minHeight: '15',
    paddingTop: '1px',
    paddingBottom: '1px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: 'black',
  },
  form__box__medium: {
    border: '1px solid brown',
    width: '176px',
    minHeight: '15',
    paddingTop: '1px',
    paddingBottom: '1px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: '10px',
    textTransform: 'capitalize',
    fontStretch: 'semi-expanded',
  },
  form__box__6: {
    border: '1px solid brown',
    width: '66px',
    minHeight: '15',
    paddingTop: '1px',
    paddingBottom: '1px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: '10px',
    textTransform: 'capitalize',
    fontStretch: 'semi-expanded',
  },
  form__box__8: {
    border: '1px solid brown',
    width: '88px',
    minHeight: '15',
    paddingTop: '1px',
    paddingBottom: '1px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: '10px',
    textTransform: 'capitalize',
    fontStretch: 'semi-expanded',
  },
  form__box__10: {
    border: '1px solid brown',
    width: '110px',
    minHeight: '15',
    paddingTop: '1px',
    paddingBottom: '1px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: '10px',
    textTransform: 'capitalize',
    fontStretch: 'semi-expanded',
  },
  form__box__11: {
    border: '1px solid brown',
    width: '121px',
    minHeight: '15',
    paddingTop: '1px',
    paddingBottom: '1px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: '10px',
    textTransform: 'capitalize',
    fontStretch: 'semi-expanded',
  },
  form__box__12: {
    border: '1px solid brown',
    width: '132px',
    minHeight: '15',
    paddingTop: '1px',
    paddingBottom: '1px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: '10px',
    textTransform: 'capitalize',
    fontStretch: 'semi-expanded',
  },
  form__box__13: {
    border: '1px solid brown',
    width: '143px',
    minHeight: '15',
    paddingTop: '1px',
    paddingBottom: '1px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: '10px',
    textTransform: 'capitalize',
    fontStretch: 'semi-expanded',
  },
  form__box__15: {
    border: '1px solid brown',
    width: '143px',
    minHeight: '15',
    paddingTop: '1px',
    paddingBottom: '1px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: '10px',
    textTransform: 'capitalize',
    fontStretch: 'semi-expanded',
  },
  form__box__17: {
    border: '1px solid brown',
    width: '143px',
    minHeight: '15',
    paddingTop: '1px',
    paddingBottom: '1px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: '10px',
    textTransform: 'capitalize',
    fontStretch: 'semi-expanded',
  },
  form__box__18: {
    border: '1px solid brown',
    width: '198px',
    minHeight: '15',
    paddingTop: '1px',
    paddingBottom: '1px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: '10px',
    textTransform: 'capitalize',
    fontStretch: 'semi-expanded',
  },
  form__box__20: {
    border: '1px solid brown',
    width: '198px',
    minHeight: '15',
    paddingTop: '1px',
    paddingBottom: '1px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: '10px',
    textTransform: 'capitalize',
    fontStretch: 'semi-expanded',
  },
  form__box__23: {
    border: '1px solid brown',
    width: '253px',
    minHeight: '15',
    paddingTop: '1px',
    paddingBottom: '1px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: '10px',
    textTransform: 'capitalize',
    fontStretch: 'semi-expanded',
  },
  form__box__25: {
    border: '1px solid brown',
    width: '275px',
    minHeight: '15',
    paddingTop: '1px',
    paddingBottom: '1px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: '10px',
    textTransform: 'capitalize',
    fontStretch: 'semi-expanded',
  },
  form__box__30: {
    border: '1px solid brown',
    width: '352px',
    minHeight: '15',
    paddingTop: '1px',
    paddingBottom: '1px',
    fontSize: '12px',
    paddingLeft: '10px',
    textTransform: 'capitalize',
    fontWeight: 'bold',
    color: 'black',
  },
  form__box__37: {
    border: '1px solid brown',
    width: '407px',
    minHeight: '15',
    paddingTop: '1px',
    paddingBottom: '1px',
    fontSize: '12px',
    paddingLeft: '10px',
    textTransform: 'capitalize',
    fontWeight: 'bold',
    color: 'black',
  },
  form__box__large: {
    border: '1px solid brown',
    width: '530px',
    minHeight: '15',
    paddingTop: '1px',
    paddingBottom: '1px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: '10px',
    textTransform: 'capitalize',
    fontStretch: 'semi-expanded',
  },
  section__separators: {
    padding: '3px 10px',
    backgroundColor: 'brown',
    marginTop: '7px',
    marginBottom: '7px',
  },
  date__employement__container: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  form__text__seperator: {
    color: 'white',
    fontSize: '12px',
    fontWeight: 'bold',
  },
  type__employement__container: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: '20px',
  },
  conti_container: {
    display: 'flex',
    gap: '15px',
  },
  account__info__msg: {
    fontSize: '10px',
    color: 'brown',
  },
  form__box__photo: {
    height: '100px',
    width: '70px',
    border: '1px solid brown',
    marginRight: '60px',
  },
  photograph: {
    height: '100px',
    width: '70px',
  },
  form__container_signature: {
    height: '70px',
    width: '150px',
    border: '1px solid brown',
    marginRight: '10px',
    overflow: 'hidden',
  },
  signature: {
    overflow: 'hidden',
  },
  add__margin__top: {
    marginTop: '20px',
  },
  pdfs_container: {
    display: 'flex',
    flexDirection: 'column',
  },
  download__container: {
    display: 'flex',
    flexDirection: 'row',
    marginTop: 20,
    width: 400,
    height: 50,
    backgroundColor: 'blue',
    paddingInline: 40,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pdf__file__name: {
    width: 100,
    marginRight: 40,
    color: 'white',
  },
  download__btn: {
    color: 'white',
  },
  privacy__notice: {
    color: 'brown',
    fontSize: '18px',
    textAlign: 'center',
    alignSelf: 'center',
    paddingTop: 20,
  },

  consent__statement: {
    fontSize: '10px',
    color: 'brown',
  },
  customer__signature: {
    fontSize: '9px',
    color: 'brown',
  },
  sign__line: {
    borderBottomColor: 'brown',
    borderBottomStyle: 'solid',
    borderBottomWidth: '1px',
    width: 100,
  },
  consent__container: {
    paddingLeft: 20,
    paddingRight: 20,
  },
  customer__sign: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  signature__date: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 25,
  },
  corporate__office: {
    fontSize: 10,
    fontWeight: 'bold',
    color: 'brown',
  },
  address__text: {
    fontSize: 8,
    color: 'brown',
  },
});

export default styles;
